

services:
  app:
    build: .
    container_name: tp-app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file: ./.env
    depends_on:
      - mongo
      - neo4j
      - redis
    command: npm run dev

  mongo:
    image: mongo:latest
    container_name: tp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  neo4j:
    image: neo4j:5
    container_name: tp-neo4j
    ports:
      - "7474:7474" # UI Web
      - "7687:7687" # Driver (Bolt)
    volumes:
      - neo4j-data:/data
    environment:
      - NEO4J_AUTH=neo4j/password123

  redis:
    image: redis:latest
    container_name: tp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  neo4j-data:
  redis-data:
